import type { Model } from "@ker-ai/protocol";

// Generated by scripts/generate-models.ts from https://models.dev/api.json.
export const models = [
	{ provider: "openai", id: "gpt-5.4", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.4-mini", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.4-nano", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.4-pro", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.5", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.5-pro", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.6-luna", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.6-sol", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai", id: "gpt-5.6-terra", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.4", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.4-mini", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.5", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.6-luna", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.6-sol", contextWindow: 272_000, maxOutputTokens: 128_000 },
	{ provider: "openai-codex", id: "gpt-5.6-terra", contextWindow: 272_000, maxOutputTokens: 128_000 },
] as const satisfies readonly Model[];
