import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE = "https://models.dev/api.json";
const CONTEXT_WINDOW = 272_000;
const MAX_OUTPUT_TOKENS = 128_000;
const publicModels = [
	"gpt-5.4",
	"gpt-5.4-mini",
	"gpt-5.4-nano",
	"gpt-5.4-pro",
	"gpt-5.5",
	"gpt-5.5-pro",
	"gpt-5.6-luna",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
] as const;
const codexModels = ["gpt-5.4", "gpt-5.4-mini", "gpt-5.5", "gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra"] as const;

interface SourceModel {
	limit?: {
		input?: number;
		output?: number;
	};
}

interface SourceProvider {
	models?: Record<string, SourceModel>;
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`models.dev returned HTTP ${response.status}`);
const source = (await response.json()) as Record<string, SourceProvider>;
const catalog = source.openai?.models;
if (!catalog) throw new Error("models.dev has no openai catalog");

const tracked = [...new Set([...publicModels, ...codexModels])];
const missing = tracked.filter((id) => !catalog[id]);
if (missing.length > 0) throw new Error(`models.dev no longer contains tracked models: ${missing.join(", ")}`);

for (const id of tracked) {
	const limits = catalog[id]?.limit;
	if ((limits?.input ?? 0) < CONTEXT_WINDOW || (limits?.output ?? 0) < MAX_OUTPUT_TOKENS) {
		throw new Error(`models.dev limits for ${id} are below the configured working limits`);
	}
}

const entries = [
	...publicModels.map((id) => ({ provider: "openai", id })),
	...codexModels.map((id) => ({ provider: "openai-codex", id })),
];
const body = `import type { Model } from "@ker-ai/protocol";

// Generated by scripts/generate-models.ts from ${SOURCE}.
export const models = [
${entries
	.map(
		({ provider, id }) =>
			`\t{ provider: "${provider}", id: "${id}", contextWindow: ${CONTEXT_WINDOW.toLocaleString("en-US").replaceAll(",", "_")}, maxOutputTokens: ${MAX_OUTPUT_TOKENS.toLocaleString("en-US").replaceAll(",", "_")} },`,
	)
	.join("\n")}
] as const satisfies readonly Model[];
`;
const directory = dirname(fileURLToPath(import.meta.url));
await writeFile(join(directory, "..", "src", "models.generated.ts"), body);
